version: '3'
services:
  backend:
    image: garden-net_utils
    ports:
      - 5000:5000
    volumes:
      - .:/garden-net_utils
    working_dir: /garden-net_utils
    restart: always
    command: 'gunicorn --workers 9 --bind unix:backend.sock wsgi:app'
