version: '3'
services:
  backend:
    image: cytoscape-utils
    ports:
      - 5000:5000
    volumes:
      - .:/cytoscape_utils
    working_dir: /cytoscape_utils
    restart: always
    command: 'gunicorn --workers 9 --bind unix:backend.sock wsgi:app'
