version: '3'
services:
  backend:
    build: .
    image: garden-net_backend
    volumes:
      - .:/garden-net_backend
      - ../garden-net/data:/garden-net_backend/data
      - tmp:/tmp/
    working_dir: /garden-net_backend
    restart: always
    command: 'gunicorn --workers 9 --bind unix:backend.sock wsgi:app'
  redis:
    image: redis:alpine
    depends_on:
      - backend
    restart: always
  celery:
    build: .
    image: garden-net_backend
    depends_on:
      - backend
      - redis
    links:
      - redis
    volumes:
      - .:/garden-net_backend
      - ../garden-net/data:/garden-net_backend/data
      - tmp:/tmp/
    working_dir: /garden-net_backend
    restart: always
    command: 'celery -A backend.celery worker -l info'

volumes:
  tmp:
