version: '3'
services:
  backend:
    image: garden-net_backend
    ports:
      - 5000:5000
    volumes:
      - .:/garden-net_backend
      - ../garden-net/data:/garden-net_backend/data
      - tmp:/tmp/
    working_dir: /garden-net_backend
    restart: always
    command: 'gunicorn --bind 0.0.0.0:5000 wsgi:app'
  redis:
    image: redis:alpine
    depends_on:
      - backend
    restart: always
  celery:
    image: garden-net_backend
    depends_on:
      - backend
      - redis
    links:
      - redis
    volumes:
      - .:/garden-net_backend
      - ../garden-net/data:/garden-net_backend/data
      - tmp:/tmp/
    working_dir: /garden-net_backend
    restart: always
    command: 'celery -A backend.celery worker -l info'

volumes:
  tmp:
